# Generated by Django 3.2 on 2021-04-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210421_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_bg',
            field=models.ImageField(default='default-bg.jpg', upload_to='profiles'),
        ),
    ]
